name: Push Commit Information

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  push-commit-info:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check current directory
        run: pwd

      - name: Download the script
        run: curl -o $PWD/process-commits.sh https://raw.githubusercontent.com/strongmind/public-reusable-workflows/main/scripts/process-commits.sh

      - name: Give script permissions
        run: chmod +x $PWD/process-commits.sh

      - name: Execute script
        run: $PWD/process-commits.sh
        env:
            REPO_NAME: ${{ github.repository }}
