name: Dev Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pulling Repo Name to use as subfolder
        run: |
          echo "REPONAME=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)" >> $GITHUB_ENV

      - name: Remove Unneeded Files
        run: |
          rm -r .github/ .git/ 

      - name: Azure Blob Storage Upload (fork)
        uses: StrongMind/azure-blob-storage-upload@main
        with:
          # The name of the storage account container these assets will be uploaded to
          container_name: "$web"
          # The name of the directory you want to upload
          source_dir: ./
          # The connection string for the storage account. Used if value is set. Either connection_string or sas_token must be supplied
          connection_string: ${{ secrets.INTERACTIVE_CONNECTION_STRING_DEV_KEY_2 }}
          # Extra arguments that can be passed to `az storage blob upload-batch|sync`. Useful for passing flags like `--pattern` or `--destination-path`
          extra_args: '--destination ${{ env.REPONAME }}/'
