name: Refresh Pulumi

on:
  workflow_call:

env:
  AWS_REGION: us-west-2

permissions:
  contents: read

jobs:
  deploy:
    name: Refresh Pulumi
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.STRONGMIND_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STRONGMIND_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd ./infrastructure/
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  
        cd ..

    - name: Refresh Pulumi
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        CONTAINER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
        WORKER_CONTAINER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        ENVIRONMENT_NAME: stage
      run: |
        cd ./infrastructure/
        pulumi login s3://pulumi-state-sm/${{ github.event.repository.name }}
        pulumi stack init stage --non-interactive || true
        pulumi stack select stage
        pulumi refresh --yes -v=3    

    - name: Refresh Pulumi
      env:
        PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        CONTAINER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
        WORKER_CONTAINER_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        ENVIRONMENT_NAME: prod
      run: |
        cd ./infrastructure/
        pulumi login s3://pulumi-state-sm/${{ github.event.repository.name }}
        pulumi stack init prod --non-interactive || true
        pulumi stack select prod
        pulumi refresh --yes -v=3