name: Build Python Package

on: 
  workflow_call:
    inputs:
      runner:
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  Build-Publish:
    name: Build and Publish
    runs-on: ${{ inputs.runner }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4 
      with:
        python-version: "3.10"

    # hardcoded pip version to avoid bug in pip 23.2 (please reference to https://strongmind.atlassian.net/browse/DEVOPS-9181?focusedCommentId=234025)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        make install

    - name: Pytest
      run: |
        make test

    - name: package files
    # major version changed during the Azure migration engagement with Caylent.
      run: |
        cd deployment
        pip install hatch
        hatch version 1.1.${{ github.run_number }}
        cd .. && make build 

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: 'dist/*'

  Upload-Package:
    name: Upload Package
    needs: Build-Publish
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        name: ${{ github.sha }}
        path: 'dist'

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{secrets.PYPITOKEN}}
